### ISSUE TITLE
Could you provide a usage example

### ISSUE THREAD

**Issue by bonelifer** [izderadicka/imap_detach#1]
I need to extract, jpg, gif or png images from an imap server. These messages will have a specified CODE in the subject to let me know these are the emails I want to get these image attachments from.  After extracting them it should mark the messages as seen.

**Comment by izderadicka** [comment]
See some samples here http://zderadicka.eu/download-email-attachments-automagically/
more detailed reference here http://zderadicka.eu/projects/python/imap_detach-tool-download-email-attachments/
So something like this should work
```
detach.py -H imap.example.com -u user -p password -v -f "/home/you/tmp/{name|subject+section}" -v --seen '(mime="image/jpg" |  mime="image/png" | mime="image/gif") &  subject ~= "CODE" '
```
