### ISSUE TITLE
Using imap_detach as python module

### ISSUE THREAD

**Issue by Epy** [izderadicka/imap_detach#11]
Hello
I'm not a skilled developper, I'm still learning Python.
I'd like a few links or documentation to use your module in other Python scripts with import if you have that.
If not, could you tell where to look in your code to find some usage possibilities

Else I'll use it with subprocess.run() but as it's already Python it would be a pity

Thank you !

**Comment by izderadicka** [comment]
Looks at imap_client.py main.     This is main logic of program.
