### ISSUE TITLE
Filter "! seen" not working on Google Workspace account

### ISSUE THREAD

**Issue by Epy** [izderadicka/imap_detach#12]
Hello
I'm using the same filter on a french ISP IMAP server and a Google Workspace (Gmail) account at work and the behaviour is different (in shell command line)
The filter I'm using
`! seen & mime="application/zip" | mime="application/gzip"`
On the french ISP IMAP I don't have any problems, files are retrieved only in unseen mails, with Gmail it retrieves absolutely all files from all emails, seen and unseen.
I let it finished the first launch over 4470 mails , it was set to mark read, which it does but for 7 mails (I don't know why but that's not important for now maybe too many mails, it won't be the case once working)

If I launch it again it will again go for all the emails and get all files (in --verbose mode it was listing all files instead of just the 7 unread)
I tried --unsafe-imap-search parameter, it didn't find any more matching emails ..
Do you have any clues ? What can I try ?

Thanks !

**Comment by Epy** [comment]
If that can help to understand or correct me if I'm making something wrong, here is the bash script I'm using.
It's the same I use personnally without any problems on a non Google IMAP server

`"python3 -m pipenv run detach.py --log-file "log.txt" --seen -H "imap.gmail.com" -u "googleworkspaceaccount@example.com" -p "SuperPassword" --folder "DMARC reports" -f "/tmp/dmarc_files/{name}" '! seen & mime="application/zip" | mime="application/gzip"' `

pipenv is only a way to have a virtualenv and launch commands in them
Did someone had some filter differences for Google accounts ?

Thanks

**Comment by izderadicka** [comment]
I have been testing it quite some time ago with google and it worked OK I think. But that's  5 years back. 
I'd recommend to try:
1. I think & operation have precedence over | - probably you want to do this:  !seen & ( mime="application/zip" | mime="application/gzip" ) - e.g. use parentheses 
2. all imap is done in imapclient package, which is pinned to quite old version 1.0.0 - try to play with it and use newer version (2. probably will not work out of box, but newer 1. might work, maybe there is some fix/improvement.
2. SEEN is quite standard flag in IMAP,   but you can also try -   - -no-imap-search to filter locally only or --seen to see if seen flag is set up for read messages.

**Comment by Epy** [comment]
Thank you for your answers
- I'll add parenthesis to try it. While waiting for your feedback I edited my detach.py call to make two instead of one, one for gzip, the second for zip.
- I'll also unlock the imapclient version and try in a new virtual env :)
- --seen command works correclty with my two calls of detach.py (will probably work with the fixed filter from 1.) 
- I'll try "--no-imap-filter" if all previous doesn't work

Thanks 👍 
I'll update my issue in a few days as soon as I'll be able to test and confirm the resolution.

**Comment by Epy** [comment]
Hi
I wasn't able to test it because lots and lots of other work more important sadly. And I changed my job two months ago. I don't need it to work on a Google account anymore.
I'll close this issue and hope it'll help someone.
