### ISSUE TITLE
Won't download JPG's

### ISSUE THREAD

**Issue by bonelifer** [izderadicka/imap_detach#2]
The example you gave me in the other issue worked for GIF and PNG, but won't download JPG's.

**Comment by bonelifer** [comment]
If I changed 
(mime="image/jpg" |  mime="image/png" | mime="image/gif")
to 
(mime~="image")

It does retrieve the JPG's.

**Comment by izderadicka** [comment]
I  missed right mime type for jpg  antually it's image/jpeg.
I.

**Comment by bonelifer** [comment]
Figured it would be something simple. Thanks for the help. This will really help in automating the automated picture frame I'm building for my mom.  Now to figure out a systemd startup file for fbi.
